; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = node

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -std=gnu++17

[env:node]
build_src_filter = -<*> +<../Arquivados/main_print_mpu6050.cpp>
; build_src_filter = +<*> -<main.cpp> -<calibration.cpp> -<esp32_multimodal_node.ino>
lib_deps = https://github.com/rfetick/MPU6050_light.git

[env:calibration]
build_src_filter = -<*> +<calibration.cpp>
