"""
Animates IMU orientation from a session CSV generated by server.py.
Complementary filter -> roll/pitch; gyro integration -> yaw.

Usage:
    python visualize.py                      # latest CSV in data/
    python visualize.py data/session_X.csv
    python visualize.py --speed 2.0          # 2x playback
"""

import argparse
import glob
import os
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from mpl_toolkits.mplot3d import Axes3D          # noqa: F401 (registers 3d projection)
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

ALPHA = 0.98  # complementary filter: weight given to gyro vs accelerometer


# ── Math helpers ──────────────────────────────────────────────────────────────

def rot(roll, pitch, yaw):
    """ZYX Euler angles (rad) → 3×3 rotation matrix."""
    cr, sr = np.cos(roll),  np.sin(roll)
    cp, sp = np.cos(pitch), np.sin(pitch)
    cy, sy = np.cos(yaw),   np.sin(yaw)
    Rz = np.array([[cy, -sy, 0], [sy,  cy, 0], [0, 0, 1]])
    Ry = np.array([[cp,  0, sp], [0,   1,  0], [-sp, 0, cp]])
    Rx = np.array([[1,   0,  0], [0,  cr, -sr], [0, sr, cr]])
    return Rz @ Ry @ Rx


def compute_angles(df):
    n  = len(df)
    ro = np.zeros(n)
    pi = np.zeros(n)
    ya = np.zeros(n)

    ax0, ay0, az0 = df['ax_g'].iloc[0], df['ay_g'].iloc[0], df['az_g'].iloc[0]
    ro[0] = np.arctan2(ay0, az0)
    pi[0] = np.arctan2(-ax0, np.sqrt(ay0**2 + az0**2))

    for i in range(1, n):
        dt = (df['t_ms'].iloc[i] - df['t_ms'].iloc[i - 1]) / 1000.0
        if dt <= 0 or dt > 1.0:
            dt = 0.2  # guard against bad timestamps

        ax, ay, az = df['ax_g'].iloc[i], df['ay_g'].iloc[i], df['az_g'].iloc[i]
        gx = np.radians(df['gx_dps'].iloc[i])
        gy = np.radians(df['gy_dps'].iloc[i])
        gz = np.radians(df['gz_dps'].iloc[i])

        accel_roll  = np.arctan2(ay, az)
        accel_pitch = np.arctan2(-ax, np.sqrt(ay**2 + az**2))

        ro[i] = ALPHA * (ro[i - 1] + gx * dt) + (1 - ALPHA) * accel_roll
        pi[i] = ALPHA * (pi[i - 1] + gy * dt) + (1 - ALPHA) * accel_pitch
        ya[i] = ya[i - 1] + gz * dt

    return ro, pi, ya


# ── Drawing helpers ───────────────────────────────────────────────────────────

# Flat PCB-shaped box vertices (local frame, centered at origin)
_L, _W, _H = 0.70, 0.50, 0.08
_BOX_V = np.array([
    [-_L/2, -_W/2, -_H/2], [ _L/2, -_W/2, -_H/2],
    [ _L/2,  _W/2, -_H/2], [-_L/2,  _W/2, -_H/2],
    [-_L/2, -_W/2,  _H/2], [ _L/2, -_W/2,  _H/2],
    [ _L/2,  _W/2,  _H/2], [-_L/2,  _W/2,  _H/2],
])
_BOX_FACES = [[0,1,2,3],[4,5,6,7],[0,1,5,4],[2,3,7,6],[0,3,7,4],[1,2,6,5]]


def draw_frame(ax, R):
    """Draw rotated box + XYZ axis arrows on a 3-D axes."""
    # Box
    vr = (R @ _BOX_V.T).T
    faces = [[vr[j] for j in face] for face in _BOX_FACES]
    poly = Poly3DCollection(faces, alpha=0.25,
                            facecolor='deepskyblue', edgecolor='steelblue', lw=0.5)
    ax.add_collection3d(poly)

    # Axis arrows (columns of R = rotated unit vectors)
    for col, color, label in zip(range(3), ['r', 'g', 'b'], ['X', 'Y', 'Z']):
        d = R[:, col]
        ax.quiver(0, 0, 0, d[0], d[1], d[2],
                  color=color, length=0.95, linewidth=2, normalize=False)
        ax.text(d[0] * 1.15, d[1] * 1.15, d[2] * 1.15,
                label, color=color, fontsize=9, fontweight='bold')


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('csv', nargs='?', help='CSV path (default: latest in data/)')
    parser.add_argument('--speed', type=float, default=1.0,
                        help='Playback speed multiplier (default: 1.0)')
    args = parser.parse_args()

    if args.csv:
        path = args.csv
    else:
        files = sorted(glob.glob('data/session_*.csv'))
        if not files:
            sys.exit('Nenhum CSV encontrado em data/. Passe o caminho como argumento.')
        path = files[-1]

    print(f'Carregando {path}')
    df = pd.read_csv(path)
    df = df.dropna(subset=['ax_g', 'ay_g', 'az_g', 'gx_dps', 'gy_dps', 'gz_dps'])
    df = df.sort_values('t_ms').reset_index(drop=True)
    print(f'{len(df)} amostras  |  duração: {(df["t_ms"].iloc[-1] - df["t_ms"].iloc[0]) / 1000:.1f} s')

    ro_rad, pi_rad, ya_rad = compute_angles(df)
    ro_deg = np.degrees(ro_rad)
    pi_deg = np.degrees(pi_rad)
    ya_deg = np.degrees(ya_rad)
    t_s    = (df['t_ms'] - df['t_ms'].iloc[0]).values / 1000.0

    # ── Layout ────────────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(14, 6))
    fig.suptitle(os.path.basename(path), fontsize=9, color='gray')

    ax3d = fig.add_subplot(1, 2, 1, projection='3d')
    ax2d = fig.add_subplot(1, 2, 2)

    # Static angle traces
    ax2d.plot(t_s, ro_deg, 'r',  lw=1,   label='Roll')
    ax2d.plot(t_s, pi_deg, 'g',  lw=1,   label='Pitch')
    ax2d.plot(t_s, ya_deg, 'b',  lw=1,   label='Yaw')
    ax2d.axhline(0, color='gray', lw=0.5, ls='--')
    ax2d.set_xlabel('Tempo (s)')
    ax2d.set_ylabel('Ângulo (°)')
    ax2d.legend(fontsize=9, loc='upper right')
    ax2d.grid(True, alpha=0.3)
    vline = ax2d.axvline(0, color='black', lw=1.5, ls='--', alpha=0.6)

    # Current-value text boxes
    txt_kw = dict(transform=ax2d.transAxes, fontsize=9, va='top',
                  bbox=dict(boxstyle='round,pad=0.3', alpha=0.15))
    t_roll  = ax2d.text(0.02, 0.98, '', color='r', **txt_kw)
    t_pitch = ax2d.text(0.02, 0.91, '', color='g', **txt_kw)
    t_yaw   = ax2d.text(0.02, 0.84, '', color='b', **txt_kw)

    # ── Animation update ──────────────────────────────────────────────────────
    def update(i):
        ax3d.cla()

        R = rot(ro_rad[i], pi_rad[i], ya_rad[i])
        draw_frame(ax3d, R)

        ax3d.set_xlim(-1, 1); ax3d.set_ylim(-1, 1); ax3d.set_zlim(-1, 1)
        ax3d.set_xlabel('X'); ax3d.set_ylabel('Y'); ax3d.set_zlabel('Z')
        ax3d.set_title(
            f'Roll {ro_deg[i]:+.1f}°   Pitch {pi_deg[i]:+.1f}°   Yaw {ya_deg[i]:+.1f}°',
            fontsize=9)
        ax3d.grid(True, alpha=0.2)

        vline.set_xdata([t_s[i], t_s[i]])
        t_roll.set_text(f'Roll  {ro_deg[i]:+.1f}°')
        t_pitch.set_text(f'Pitch {pi_deg[i]:+.1f}°')
        t_yaw.set_text(f'Yaw   {ya_deg[i]:+.1f}°')

        return []

    interval_ms = max(16, int(np.median(np.diff(df['t_ms'].values)) / args.speed))
    ani = animation.FuncAnimation(           # noqa: F841  (keep reference alive)
        fig, update, frames=len(df), interval=interval_ms, blit=False)

    plt.tight_layout()
    plt.show()


if __name__ == '__main__':
    main()
